cluster:
  name: freetier-02
  image:
    repository: registry.cn-shanghai.aliyuncs.com/matrixorigin/matrixone
  version:
    from:
    to: nightly-a6e7ae3b
  pluginImage: registry.cn-hangzhou.aliyuncs.com/ack-cos/plugin:49e2ffd8-20240201
  unit: qa-unit-cn-hangzhou
  provider: aliyun
  region: cn-hangzhou
  storageClassName: alicloud-disk-essd-pl1
  objectStorage:
    bucket: mo-qa
    region: cn-hangzhou
    path:
timestamp:
action:
moBackup:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/yidao-test/mo-backup
    tag: old
    pullSecret: mo-backup-test
  backup:
    cluster:
      name:
      version:
    dir: s3
    endpoint: http://oss-cn-hangzhou-internal.aliyuncs.com
    bucket: backup-test-bucket
    filePath: ""
    region: cn-hangzhou
    # host: 127.0.0.1
    # port: 6001
    # user: dump
    # password:
    # access_key_id: ""
    # secret_access_key: ""
    # parallelism: 10
  restore:
    cluster:
      name:
      version:
    dir: s3
    endpoint: http://oss-cn-hangzhou-internal.aliyuncs.com
    bucket: backup-test-bucket
    filePath: ""
    region: cn-hangzhou
    # access_key_id: ""
    # secret_access_key: ""
