name: MO BVT Tests

on:
  workflow_dispatch:
    inputs:
        env:
          description: Target environment
          required: true
          type: choice
          options:
            - qa
            - dev
          default: qa
        host:
          description: MO Host
          required: true
          type: string
        port:
          description: MO Port
          required: true
          type: string
          default: '6001'
        account:
          description: MO Account
          required: false
          type: string
        password:
          description: Password of MO Account
          required: true
          type: string
          default: Admin123
        sys:
          description: MO sys
          required: true
          type: string
          default: dump
        sys-password:
          description: Password of MO sys
          required: true
          type: string
        bvt_cases:
          description: Tests path in matrixone for BVT
          required: true
          type: string
          default: matrixone/test/distributed/cases
        bvt_extra_args:
          description: Run BVT tests with extra args
          required: true
          type: string
          default: '-n -g'
jobs:
  bvt-test:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
    timeout-minutes: 60

    steps:
      - name: Set Up Java1.8
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '8'
      
      - uses: ConorMacBride/install-package@v1
        with:
          apt: mysql-client

      - name: Checkout matrixone
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/matrixone
          ref: main
          path: 2.0-dev
          token: ${{ secrets.GH_PAT }}

      - name: Checkout mo-tester
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mo-tester
          ref: main
          path: mo-tester
          token: ${{ secrets.GH_PAT }}
          # fetch-depth: '3'

      - name: Start BVT Test
        id: bvt_on_pr_version
        run: |
          set -x
          # dbs=$(MYSQL_PWD=${{ inputs.sys-password }} mysql -h ${{ inputs.host }} -P ${{ inputs.port }} -u ${{ inputs.sys }}  -e "show databases" --skip-column-names | awk '{print $1}')
          # dbs="${dbs//$'\n'/,}"
          locale
          dbs=
          for db in $(MYSQL_PWD=${{ inputs.sys-password }} mysql -h ${{ inputs.host }} -P ${{ inputs.port }} -u ${{ inputs.sys }}  -e "show databases" --skip-column-names | awk '{print $1}'); do
            if [ ! $db = "test" ]; then
              dbs="$dbs,$db"
            fi
          done
          dbs=${dbs:1}
          # timedatectl status
          # sudo timedatectl set-timezone "Asia/Shanghai"
          # timedatectl status
          # sleep 60s
          cd $GITHUB_WORKSPACE/mo-tester
          # ./run.sh -c 2>&1 | tee result.log
          # if [ "$(cat ./result.log | grep -i -E 'WARN|ERROR' | grep -v "grep" | wc -l)" -gt 0 ]; then echo 'case format check failed.'; exit 1; fi
          sed -i.bak "s/\(^builtindb:\).*/\1 $dbs/" run.yml
          sed -i.bak \
          -e 's/socketTimeout:.*/socketTimeout: 300000/' \
          -e 's/\(serverTimezone:\).*/\1 "UTC"/' \
          -e 's/127.0.0.1:6001/${{ inputs.host }}:${{ inputs.port }}/' \
          -e 's/\(name:\).*/\1 "${{ inputs.sys }}"/' \
          -e 's/\(password:\).*/\1 "${{ inputs.sys-password }}"/' \
          -e 's/\(sysuser:\).*/\1 "${{ inputs.sys }}"/' \
          -e 's/\(syspass:\).*/\1 "${{ inputs.sys-password }}"/' \
          mo.yml
          cat mo.yml
          cat run.yml
          # ./run.sh -p $GITHUB_WORKSPACE/${{ inputs.bvt_cases }} ${{ inputs.bvt_extra_args }} 2>&1

          exclude_tests=optimistic
          cases_path=$GITHUB_WORKSPACE/${{ inputs.bvt_cases }}
          if [ -d $cases_path ]; then
            if [ ${cases_path: -1} = '/' ]; then
              cases_path=${cases_path%?}
            fi
            find $cases_path -type f ! -name "*.result" -exec sed -i 's/user=\(.*\)dump\&password=.*/user=\1dump\&password=${{ inputs.sys-password }}/g' {} \;
            for exclude in $(find $cases_path -type f ! -name "*.result" -exec grep -l "\$resources" {} \;); do
              exclude_tests="${exclude_tests},${exclude##*cases/}"
            done
            echo "Exclude tests to run: ${exclude_tests}"
          elif [ -f $cases_path ]; then
            sed -i.bak 's/user=\(.*\)dump\&password=.*/user=\1dump\&password=${{ inputs.sys-password }}/g' $cases_path
          else
            echo "The cases path must be file or directory."
            exit 1
          fi
          echo $cases_path
          ./run.sh -p $cases_path -e ${exclude_tests} ${{ inputs.bvt_extra_args }}

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: bvt_tests_results
          path: |
            ${{ github.workspace }}/mo-tester/log/
            ${{ github.workspace }}/mo-tester/report/
          retention-days: 7
