name: Load Data

on:
  workflow_dispatch:
    inputs:
      env:
        description: Target environment
        required: true
        type: choice
        options:
          - qa
          - dev
        default: qa
      data-category:
        description: What data to load
        type: choice
        required: true
        options:
          - all
          - tpch
          - tpcc
          - sysbench
          - bigdata
          - scale
        default: all
      mo-host:
        description: Host for mo instance
        required: true
        type: string
      mo-port:
        description: Port for mo instance
        required: false
        type: number
        default: 6001
      mo-user:
        description: User name of mo instance
        required: true
        type: string
        default: dump
      mo-password:
        description: Password of mo instance
        required: true
        type: string
        default: Admin123
      data-size:
        description: Size of data
        type: choice
        required: true
        options:
          - 100M
          - 1B
          - '1'
          - '10'
          - '100'
          - '1000'
          - '10000'
        default: 100M

jobs:
  load-bigdata:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env || 'qa' }}
    timeout-minutes: 120
    if: inputs.data-category == 'bigdata'
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: mysql-client

      - name: Checkout mo-nightly-regression
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mo-nightly-regression
          ref: big_data
          path: mo-nightly-regression
          token: ${{ secrets.GH_PAT }}

      - name: Set Up Python3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          cd $GITHUB_WORKSPACE/mo-nightly-regression/tools/mo-regression-test
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Data
        run: |
          cd $GITHUB_WORKSPACE/mo-nightly-regression/tools/mo-regression-test
          sed -i.bak \
          -e 's#\${ENDPOINT}#http://cos.ap-guangzhou.myqcloud.com#g' \
          -e 's/\${ACCESS_KEY_ID}/${{ secrets.COS_AK }}/g' \
          -e 's/\${SECRET_ACCESS_KEY}/${{ secrets.COS_SK }}/g' \
          cases/big_data_test/02_LOAD_DATA/01_load_basic_for_${{ inputs.data-size }}.sql
          mysql \
          -h ${{ inputs.mo-host }} \
          -P ${{ inputs.mo-port }} \
          -u ${{ inputs.mo-user }} \
          -p${{ inputs.mo-password }} \
          -e "drop database if exists big_data_test;drop database if exists ssb_100G;"
          echo "$(date '+%Y-%m-%d %T') - Create Database and Tables"
          python run.py \
          -H ${{ inputs.mo-host }} \
          -P ${{ inputs.mo-port }} \
          -u ${{ inputs.mo-user }} \
          -p ${{ inputs.mo-password }} \
          -c ./cases/big_data_test/01_CREATE_TABLE
          echo "$(date '+%Y-%m-%d %T') - Start to Load Data"
          python run.py \
          -H ${{ inputs.mo-host }} \
          -P ${{ inputs.mo-port }} \
          -u ${{ inputs.mo-user }} \
          -p ${{ inputs.mo-password }} \
          -c ./cases/big_data_test/02_LOAD_DATA/01_load_basic_for_${{ inputs.data-size }}.sql

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bigdata-test-logs
          path: |
            ${{ github.workspace }}/mo-nightly-regression/tools/mo-regression-test/*.log
            ${{ github.workspace }}/mo-nightly-regression/tools/mo-regression-test/report/
          retention-days: 7

  load-tpch-data:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env || 'qa' }}
    timeout-minutes: 120
    if: inputs.data-category == 'all' || inputs.data-category == 'tpch'
    steps:
      - name: Checkout mo-load-data
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mo-load-data
          ref: main
          path: mo-load-data
          token: ${{ secrets.GH_PAT }}

      - uses: ConorMacBride/install-package@v1
        with:
          apt: mysql-client

      - name: Load TPCH Data
        run: |
          set -uo pipefail
          cd $GITHUB_WORKSPACE/mo-load-data
          #if [ ${{ inputs.aliyun }} = 'true' ]; then
          #  endpoint=oss-cn-hangzhou-internal.aliyuncs.com
          #else
          #  endpoint=oss-cn-hangzhou.aliyuncs.com
          #fi
          endpoint=cos.ap-guangzhou.myqcloud.com
          if [ ${{ inputs.data-size }} = '1' ]; then
            database=tpch_100
          elif [ ${{ inputs.data-size }} = '100' ]; then
            database=tpch_100
          elif [ ${{ inputs.data-size }} = '1000' ]; then
            database=tpch_1000
          else
            database=tpch_10
          fi
          sed -i \
          -e "s/\(ENDPOINT:\).*/\1 $endpoint/" \
          -e 's/\(ACCESS_KEY_ID:\).*/\1 ${{ secrets.COS_AK }}/' \
          -e 's/\(SECRET_ACCESS_KEY:\).*/\1 ${{ secrets.COS_SK }}/' \
          access.yml
          ./load.sh \
          -c cases/00_from_s3/$database -d $database -m -r \
          -b mo-load-guangzhou-1308875761 \
          -h ${{ inputs.mo-host }} \
          -P ${{ inputs.mo-port }} \
          -u ${{ inputs.mo-user }} \
          -p ${{ inputs.mo-password }} \
          2>&1 | tee load-tpch-data.log

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tpch-test-logs
          path: |
            ${{ github.workspace }}/mo-load-data/*.log
            ${{ github.workspace }}/mo-load-data/report/
          retention-days: 7