name: Study and Test

on:
  workflow_dispatch:

jobs:
  moc-test:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout mocloud-tester
        uses: actions/checkout@v3
        with:
          repository: TangxingZhou/workflow-test
          ref: main

      - name: Echo github workspace
        run: |
          echo $GITHUB_WORKSPACE

      - name: Set up Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

#      - name: Set up Java1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8

      - name: Install Allure
        run: |
          export ALLURE_VERSION=2.20.0
          curl -o allure-$ALLURE_VERSION.tgz -sL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/$ALLURE_VERSION/allure-commandline-$ALLURE_VERSION.tgz
          sudo tar -zxvf allure-$ALLURE_VERSION.tgz -C /usr/local/bin/
          sudo ln -s /usr/local/bin/allure-$ALLURE_VERSION/bin/allure /usr/bin/allure

      - name: Install Python Dependencies
        run: |
          cd $GITHUB_WORKSPACE/moc-tester
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Aliyun Tests Case
        run: |
          cd $GITHUB_WORKSPACE/moc-tester
          pytest src/tests/test_k8s_api.py --alluredir=./allure-results
        env:
          env: qa
          provider: aliyun
          region: cn-hangzhou
          k8s_unit_config: ${{secrets.K8S_UNIT_CONFIG}}
          # k8s_unit_host: ${{secrets.K8S_UNIT_HOST}}
          # k8s_unit_ca_cert: ${{secrets.K8S_UNIT_CA_CERT}}
          # k8s_unit_user_cert: ${{secrets.K8S_UNIT_USER_CERT}}
          # k8s_unit_user_key: ${{secrets.K8S_UNIT_USER_KEY}}
          k8s_controller_config: ${{secrets.K8S_CONTROLLER_CONFIG}}
          # k8s_controller_host: ${{secrets.K8S_CONTROLLER_HOST}}
          # k8s_controller_ca_cert: ${{secrets.K8S_CONTROLLER_CA_CERT}}
          # k8s_controller_user_cert: ${{secrets.K8S_CONTROLLER_USER_CERT}}
          # k8s_controller_user_key: ${{secrets.K8S_CONTROLLER_USER_KEY}}
