name: Migrate mo-2.0
on:
  workflow_dispatch:
    inputs:
      env:
        description: "environment"
        default: dev
        required: true
        type: choice
        options:
          - qa
          - dev
      mo-cluster:
        description: 'mo cluster to migrate'
        default: restore-freetier-01
        required: true
        type: string
      upgrade-version:
        description: 'version to upgrade'
        required: true
        type: string
      ckp-version:
        description: 'version of MO CKP'
        default: v1.2.3-7944ef014-2024-10-17
        required: true
        type: string
      migrate-tag:
        description: 'migrate image tag'
        default: '3288fb5'
        required: true
        type: string

jobs:
  build-mo-image:
    uses: ./.github/workflows/build-images.yaml
    secrets: inherit
    with:
      organization: matrixorigin
      project: matrixone
      ref: 2.0-dev
      dockerfile: ./optools/images/Dockerfile
      tag: v2.0.1

  build-migrate-image:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env || 'qa' }}
    outputs:
      image-repo: ${{ steps.prep.outputs.image-repo }}
      image-tag: ${{ steps.prep.outputs.image-tag }}
    steps:
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/amd64,linux/arm64

      - name: Set Up Docker Buildx
        id: buildx
        uses:  docker/setup-buildx-action@v3

      - name: Login to Hangzhou Alicloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Checkout migrate Repo
        uses: actions/checkout@v4
        with:
          repository: Wenbin1002/matrixone
          ref: migrate
          token: ${{ secrets.GH_PAT }}

      - name: Prepare
        id: prep
        run: |
          git status
          repo_tag=$(git rev-parse --short HEAD)
          repo_tag=${repo_tag::7}
          echo "image-repo=registry.cn-hangzhou.aliyuncs.com/mocloud/mo-migrate:${repo_tag}" >> $GITHUB_OUTPUT
          echo "image-tag=${repo_tag}" >> $GITHUB_OUTPUT
          cat > Dockerfile << EOF
          FROM golang:1.23.0-bookworm as builder

          # goproxy
          ARG GOPROXY="https://proxy.golang.org,direct"
          RUN go env -w GOPROXY=\${GOPROXY}

          RUN mkdir -p /go/src/github.com/matrixorigin/matrixone

          WORKDIR /go/src/github.com/matrixorigin/matrixone

          COPY go.mod go.mod
          COPY go.sum go.sum
          RUN go mod download

          COPY . .

          RUN make mo-migrate

          FROM ubuntu:22.04

          COPY --from=builder /go/src/github.com/matrixorigin/matrixone/mo-migrate /mo-migrate
          COPY --from=builder /go/src/github.com/matrixorigin/matrixone/etc /etc

          RUN apt-get update && apt-get install -y \
            dnsutils \
            curl \
            git \
            && apt-get clean && rm -rf /var/lib/apt/lists/*

          WORKDIR /

          EXPOSE 6001
          EOF
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.prep.outputs.image-repo }}

  migrate:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env || 'qa' }}
    permissions:
      contents: write
    needs:
      - build-migrate-image
      - build-mo-image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout mocloud-tester
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mocloud-tester
          path: mocloud-tester
          ref: qa-txzhou
          token: ${{ secrets.GH_PAT }}

      - name: Set Up Python3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
  
      - name: Install Python Dependencies
        run: |
          cd $GITHUB_WORKSPACE/mocloud-tester
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Migrate & Upgrade MO
        run: |
          cp migrate-2.0.py $GITHUB_WORKSPACE/mocloud-tester/src/upgrade/
          cd $GITHUB_WORKSPACE/mocloud-tester
          if [ $(uname -m) = 'x86_64' ]; then
            curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          fi
          chmod +x ./mc
          ./mc alias set oss http://oss-cn-hangzhou.aliyuncs.com $RESTORE_ALIYUN_AK $RESTORE_ALIYUN_SK
          export PYTHONPATH=$(pwd)
          python src/upgrade/migrate-2.0.py \
          --cluster-name ${{ inputs.mo-cluster }} \
          --upgrade-version ${{ needs.build-mo-image.outputs.image-tag || inputs.upgrade-version }} \
          --ckp-version ${{ inputs.ckp-version }} \
          --migrate-tag ${{ needs.build-migrate-image.outputs.image-tag || inputs.migrate-tag }}
        env:
          email: ${{ vars.UPGRADE_TEST_EMAIL }}
          password: ${{ secrets.UPGRADE_TEST_PASSWORD }}
          database_platform_password: ${{ secrets.DATABASE_PLATFORM_PASSWORD }}
          management_platform_url: ${{ secrets.MANAGEMENT_PLATFORM_URL }}
          management_platform_user: ${{ secrets.MANAGEMENT_PLATFORM_USER }}
          management_platform_password: ${{ secrets.MANAGEMENT_PLATFORM_PASSWORD }}
          env: ${{ inputs.env || 'qa' }}
          provider: aliyun
          region: cn-hangzhou
          k8s_unit_config: ${{ secrets.K8S_UNIT_CONFIG }}
          k8s_controller_config: ${{ secrets.K8S_CONTROLLER_CONFIG }}
          RESTORE_ALIYUN_AK: ${{ secrets.RESTORE_ALIYUN_AK }}
          RESTORE_ALIYUN_SK: ${{ secrets.RESTORE_ALIYUN_SK }}

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: migrate-test-logs
          path: |
            ${{ github.workspace }}/mocloud-tester/moc-migrate-test.log
          retention-days: 7
