name: To Test

on:
  workflow_dispatch:
jobs:
  restore:
    runs-on: ubuntu-latest
    environment:
      name: qa
    outputs:
      mo-host: ${{ steps.restore.outputs.mo-host }}
      mo-port: ${{ steps.restore.outputs.mo-port }}
      mo-user: ${{ steps.restore.outputs.mo-user }}
      mo-password: ${{ steps.restore.outputs.mo-password }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: tests
      - name: Set Up Python3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Checkout mo-load
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mo-load
          ref: main
          path: mo-load
          token: ${{ secrets.GH_PAT }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mo-sysbench
          path: mo-sysbench
          token: ${{ secrets.GH_PAT }}
      - name: Set up Java1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
    #   - name: Restore MOC From Backup
    #     if: ${{ vars.UPGRADE_TEST_ACTION == 'restore' }}
    #     id: restore
    #     run: |
    #       if [ -z $MOC_INSTANCE_HOST ]; then
    #         echo "mo-host=" >> $GITHUB_OUTPUT
    #       else
    #         echo "mo-host=${MOC_INSTANCE_HOST}" >> $GITHUB_OUTPUT
    #       fi
    #       if [ -z $MOC_INSTANCE_PORT ]; then
    #         echo "mo-port=" >> $GITHUB_OUTPUT
    #       else
    #         echo "mo-port=${MOC_INSTANCE_PORT}" >> $GITHUB_OUTPUT
    #       fi
    #       if [ -z $MOC_INSTANCE_USER ]; then
    #         echo "mo-user=" >> $GITHUB_OUTPUT
    #       else
    #         echo "mo-user=${MOC_INSTANCE_USER}" >> $GITHUB_OUTPUT
    #       fi
    #       if [ -z $MOC_INSTANCE_PASSWORD ]; then
    #         echo "mo-password=" >> $GITHUB_OUTPUT
    #       else
    #         echo "mo-password=${MOC_INSTANCE_PASSWORD}" >> $GITHUB_OUTPUT
    #       fi
    #     env:
    #       MOC_INSTANCE_HOST: 127.0.0.1
    #       MOC_INSTANCE_PORT: 6001
    #       MOC_INSTANCE_USER: dump
    #       MOC_INSTANCE_PASSWORD: 123
      - name: Backup MO Data
        id: restore
        run: |
          cd $GITHUB_WORKSPACE/tests
          export PYTHONPATH=$(pwd)
          env
          python test.py
      - uses: ConorMacBride/install-package@v1
        with:
          apt: mysql-client
      - name: Test
        if: steps.restore.outputs.mo-host && steps.restore.outputs.mo-port && steps.restore.outputs.mo-user && steps.restore.outputs.mo-password
        shell: bash
        run: |
          echo "export ZTX_TEST='hello'" >> ~/.bashrc
          echo "hello 123" > test.log
          echo ${{ steps.restore.outputs.mo-host }}
          echo ${{ steps.restore.outputs.mo-port }}
          echo ${{ steps.restore.outputs.mo-user }}
          echo ${{ steps.restore.outputs.mo-password }}
          # mysql -h ${{ steps.restore.outputs.mo-host }} -P ${{ steps.restore.outputs.mo-port }} -u ${{ steps.restore.outputs.mo-user }} -p${{ steps.restore.outputs.mo-password }}
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: upgrade-test-logs
          path: |
            ${{ github.workspace }}/*.log
          retention-days: 7
    #   - name: Run Sysbench Tests
    #     run: |
    #       tree
    #       # cd $GITHUB_WORKSPACE/mo-sysbench
    #       # sysbench --mysql-host=$MO_HOST --mysql-port=$MO_PORT --mysql-user=$MO_USER --mysql-password=$MO_PASSWORD oltp_common.lua --mysql-db=sysbench_db --tables=10 --table_size=100000 --threads=1 --time=30 --report-interval=10 --create_secondary=off --auto_inc=off prepare
    #       cd $GITHUB_WORKSPACE/mo-load
    #       ./start.sh \
    #       -m SYSBENCH \
    #       -n 10 \
    #       -s 100000 \
    #       -h restore-freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech \
    #       -P 6001 \
    #       -u 018f7a51_3c66_7991_8402_37c1c0d47263:admin:accountadmin \
    #       -p Admin123 \
    #       -b sbtest
    #       RUNNER_TRACKING_ID="" && \
    #       nohup ./start.sh \
    #       -c cases/sysbench/mixed_10_100000/ \
    #       -t 10 \
    #       -d 1 \
    #       -h restore-freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech \
    #       -P 6001 \
    #       -u 018f7a51_3c66_7991_8402_37c1c0d47263:admin:accountadmin \
    #       -p Admin123 \
    #       -b sbtest \
    #       -g > sysbench.log &
    #   - name: Upload Logs
    #     uses: actions/upload-artifact@v4
    #     if: always()
    #     with:
    #       name: upgrade-test-logs
    #       path: |
    #         ${{ github.workspace }}/mo-load/sysbench.log
    #       retention-days: 7
    #   - name: Prepare data
    #     run: |
    #       sysbench \
    #       --mysql-host=restore-freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech \
    #       --mysql-port=6001 \
    #       --mysql-user=018f7a51_3c66_7991_8402_37c1c0d47263:admin:accountadmin \
    #       --mysql-password=Admin123 \
    #       oltp_common.lua \
    #       --mysql-db=sysbench_db \
    #       --tables=10 \
    #       --table_size=100 \
    #       --threads=1 \
    #       --time=30 \
    #       --report-interval=10 \
    #       --create_secondary=off \
    #       --auto_inc=off \
    #       prepare
    #   - name: Run OLTP readonly
    #     run: |
    #       sysbench \
    #       --mysql-host=restore-freetier-01.cn-hangzhou.cluster.cn-qa.matrixone.tech \
    #       --mysql-port=6001 \
    #       --mysql-user=018f7a51_3c66_7991_8402_37c1c0d47263:admin:accountadmin \
    #       --mysql-password=Admin123 \
    #       --db-ps-mode=disable \
    #       oltp_read_only.lua \
    #       --mysql-db=sysbench_db \
    #       --tables=10 \
    #       --table_size=100 \
    #       --threads=10 \
    #       --time=30 \
    #       --report-interval=10 \
    #       --create_secondary=off \
    #       --auto_inc=off \
    #       --skip_trx=on \
    #       --range_selects=off \
    #       --point_selects=1 \
    #       run

  test:
    runs-on: ubuntu-latest
    environment:
      name: qa
    needs:
      - restore
    steps:
      - name: Test
        shell: bash
        if: needs.restore.outputs.mo-host && needs.restore.outputs.mo-port && needs.restore.outputs.mo-user && needs.restore.outputs.mo-password
        run: |
          echo "hello 456" > test.log
          echo ${{ needs.restore.outputs.mo-host }}-${{ needs.restore.outputs.mo-port }}-${{needs.restore.outputs.mo-user }}-${{ needs.restore.outputs.mo-password }}
          echo ${{ needs.restore.outputs.mo-host1 || needs.restore.outputs.mo-user1 || 'Admin123' }}
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: upgrade-test1-logs
          path: |
            ${{ github.workspace }}/*.log
