name: Study and Test

on:
  schedule:
    - cron: '22 7 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: The action to perform
        required: true
        type: choice
        options:
          - backup
          - restore
          - upgrade
        default: restore

jobs:
  moc-test:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout mocloud-tester
        # if: ${{ inputs.action == 'backup' }}
        # if: ${{ github.event_name == 'schedule' }}
        if: ${{ github.event_name == 'workflow_dispatch' && contains(['restore', 'upgrade', inputs.action])}}
        run: |
          echo 123
      - name: Checkout mocloud-tester
        if: ${{ inputs.action == 'restore' || inputs.action == 'upgrade' }}
        run: |
          echo 456

