name: To Test

on:
  workflow_dispatch:
jobs:
  build-mo-image:
    runs-on: ubuntu-latest
    environment:
      name: qa
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: matrixorigin/mo-sysbench
          token: ${{ secrets.GH_PAT }}
      
      - name: Print
        run: |
          apt install -y sysbench
          sysbench --help
