name: Study and Test

on:
  schedule:
    - cron: '20 15 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: The action to perform
        required: true
        type: choice
        options:
          - backup
          - restore
          - upgrade
        default: restore

jobs:
  moc-test:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Checkout mocloud-tester
        if: ${{ inputs.action == 'backup' }}
        run: |
          echo 123
      - name: Checkout mocloud-tester
        if: ${{ inputs.action == 'restore' || inputs.action == 'upgrade' }}
        run: |
          echo 456

